### ISSUE TITLE
Bearer backend not piping options to 'ensure user from token'.

### ISSUE THREAD

**Issue by MJJH** [Mimetis/aad_fastapi#5]
**Describe the bug**
In the AadBearerBackend, the ensure_user_from_token gets called, but does not provide the selected options. Therefor the method will try to create new options, but since I don't use the environment setup, it won't work. 

**Expected behavior**
I'd like to suggest in aad_bearer_backend.py, r46 to change to 
`user = ensure_user_from_token(auth_token, options=self.options, public_key=self.public_key)`

**Comment by dorlugasigal** [comment]
good catch, i will add it

**Comment by Mimetis** [comment]
thanks @dorlugasigal 
You are too fast !!

**Comment by dorlugasigal** [comment]
fixed, you can use version [1.0.5](https://pypi.org/project/aad-fastapi/1.0.5/) with the fixed code
