### ISSUE TITLE
Roles folder is not installed

### ISSUE THREAD

**Issue by julyvee** [Mimetis/aad_fastapi#8]
**Describe the bug**
I installed the aad_fastapi package with pip, as mentioned and added it to my api as described in the Readme. But when I try to run the api, I get an error saying that the .roles module cannot be found. 

`ModuleNotFoundError: No module named 'aad_fastapi.roles'`

I investigated further and I can see that the roles folder was not downloaded when I installed the package. 

**To Reproduce**
1. Install the package locally with pip
2. Add authentication to API as described in Readme
3. Try to run API with the launch.json example

**Expected behavior**
API runs and doesn't throw an error

**Screenshots**
![Screenshot 2023-07-20 at 10 35 52](https://github.com/Mimetis/aad_fastapi/assets/10207075/bacad841-c04f-4c6f-bdfe-f381671c86f6)
![Screenshot 2023-07-20 at 10 34 59](https://github.com/Mimetis/aad_fastapi/assets/10207075/df491b39-b51b-4cbc-a534-de07b7597052)

**Additional context**
Running in ubuntu devcontainer

**Comment by dorlugasigal** [comment]
Hey @julyvee, please make sure to install the latest version of aad-fastapi,
I've tested it on my machine, from scratch on a python 3.7 venv, and aad-fastapi exists with roles modules

**Comment by julyvee** [comment]
Yes it works now in the newest version 1.1.2, the roles folder is installed correctly. Thanks!
